config/routes.rb
MyCharacterTypes::Application.routes.draw do
  
  root to: 'static_pages#home'

  get '/',         to: 'static_pages#home',     as: :home
  get '/help',     to: 'static_pages#help',     as: :help
  get '/about',    to: 'static_pages#about',    as: :about
  get '/contact',  to: 'static_pages#contact',  as: :contact

  
  get '/signup',        to: 'users#new',           as: :signup
  get "/profile/:id",   to: 'users#show',          as: :profile
  resources :users
  
  get     '/login',     to: 'sessions#new',        as: :login
  delete  '/logout',    to: 'sessions#destroy',    as: :logout
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
	require 'bcrypt'

	# Validations for name attribute.
	#! Should not allow space characters...
	USERNAME_REGEX = /[\w]+/i
	validates :username, 	presence: true, 
										uniqueness: { case_sensitive: false },
										length: { within: 4..25 },
										format: { with: USERNAME_REGEX }
										#disallow symbols by using regex
										#disallw space character

	# Validations for email attribute.
	before_save { email.downcase! }
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
										uniqueness: { case_sensitive: false },
										format: { with: EMAIL_REGEX }
										
	# Validations for password attribute, and securing password.
	# Takes care of password confirmation matching.
	has_secure_password 
	validates :password, presence: true,
											 length: { minimum: 6 }

	# Tokens
  before_create :create_remember_token

  def User.new_remember_token
  	SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end

  private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
  #use rescue to redirect away from exception error page when double clicking form rapidly
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Enables sessions methods throught the app
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# not storing previous location properly. seems to store the get sessions/new location
before_action :store_location, only: [:new]

	def new
		redirect_to user_path(current_user) if logged_in?
		#@session ||= Session.new
		#@user ||= User.find_by(email: params[:session][:email])
		#! Don't allow users to go to signup page via "back" when logged in.
		#! Nevermind It's fine. Session will be replaced, not two-at-once.
	end

	def create
		#! Do this using email index
		user = User.find_by(email: params[:session][:email].downcase)
		correct_password = user.authenticate(params[:session][:password]) unless user.nil?
		if user && correct_password
			log_in user
			redirect_back_or root_url
		else
			flash.now[:error] = 'Invalid email/password combination.'			
			render '/sessions/new'
		end
		#@session = Session.new(session_params)
		#if  
		#else 
		#end
		
	end
	
	def destroy
		log_out
		#! Redirect to last viewed page
		store_location
		redirect_back_or root_url
	end

	#private 
	#
	#def session_params
	#	#! also allow username
	#	#! detect if username or email via presence of @ symbol, or non word characters
	#	@session.require(:session).permit(:email,:password)
	#end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:edit, :update, :index]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: [:destroy]

  def index
  	@users = User.paginate(:page => params[:page])
  end

  def show
  	#change to find by username index
  	@user = User.find(params[:id])
    #! Prevent page from being as if logged in after logging out and pressing "back". Implement at sitewide session level?
  end

  def new
  	@user = User.new
  	#! Don't allow users to go to login page via "back" when logged in.
  end

  def create
  	@user = User.new(user_params)	 
	  if @user.save
      log_in @user
      flash[:success] = "Welcome to My Character Types!"
	  	redirect_to @user
	  else
      #! why does this result in the url being user/ url?
      #! why does changing this to render 'edit' not work? cause
	  	render 'new'
	  end
	  #disallow if logged, exception being admin
  end

  def edit
  	@user = User.find(params[:id])
  	#! require proper user session or admin
  end

  def update
  	@user = User.find(params[:id])
  	#! don't require password for updating normal fields.
    #! changing username, email, or password should require current password and confirmation.
    if @user.update(params[:user].permit(:username,:email,:password,:password_confirmation))
  		flash[:success] = "Profile updated."
      redirect_to @user
  	else
  		render 'edit'
  	end
  	#! require proper user session or admin
  end

  def destroy
  	@user = User.find(params[:id]).destroy
    flash[:success] = "User deleted."
  	redirect_to users_path
  	#! require proper user session or admin
  end

  private
    # whitelist form fields entered by users
    def user_params
  	  params.require(:user).permit(:username, 
                                   :email, 
                                   :password, 
                                   :password_confirmation)
    end

    def logged_in_user
      if !logged_in?
        store_location
        redirect_to login_url, notice: "Please log in." unless logged_in?
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless (current_user.admin == true)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title)
	base_title = "My Character Types"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_out
		current_user.update_attribute(:remember_token, 
																	User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end	

	def log_in(the_user)
		# Create new token.
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		# Update_attribute bypasses validations.
		# Bypassing validations is necessary here a required password is absent in the inputs
		the_user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = the_user
	end

	def logged_in?
		!current_user.nil?
	end	

	def current_user
		# Local remember_token variable encrypts token value stored in cookie.
		remember_token = User.encrypt(cookies[:remember_token])
		# Find user whose remember_token attribute value matches the encrypted result of the token stored in the cookie.
		# Using ||= handles login as well as navigating pages during the session.
		# Doesn't hit database if value is already set - checks value before quering. Good!
		# ||= here uses short-circuit evaluation.
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user=(the_user)
		@current_user = the_user
	end

	def current_user? (the_user)
		the_user == current_user
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def redirect_back_or(default_page)
		redirect_to(session[:return_to] || default_page)
		session.delete(:return_to)
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 100})
		size = options[:size]
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class:"gravatar")
	end
	
end

app/views/layouts/_footer.html.erb
<footer>
	<ul>
		<li>Copyright</li>
		<li><%#= link_to "Contact",  %></li>
		<li><%= link_to "About", about_path %></li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% link_to 'logo image', root_path %>
</header>

app/views/layouts/_navbar.html.erb
<nav>
<ul>
	<li><%= link_to 'Home', home_path %></li>	
	<li><%= link_to 'Universes', '#' %></li>
	<li><%= link_to 'Characters', '#' %></li>
	<li><%= link_to 'Celebrities', '#' %></li>
	<li><%= link_to 'Members', users_path %></li>
	<li><%= link_to 'Socionics', '#' %></li>
	<li><%= link_to 'Tools', '#' %></li>
</ul>
<ul class="pull-right">	
	<% if logged_in? %>
		<li><%= link_to current_user.username, current_user %></li>
		<li><%= link_to 'Log Out', logout_path, method: 'delete' %></li>
	<% else %>
		<li><%= link_to 'Log In', login_path %></li>
		<li><%= link_to 'Create Account', signup_path %></li>
	<% end %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/header' %>
<%= render '/layouts/navbar' %>

<aside class="sidebar">
</aside>

<main>
	<% flash.each do |key,value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
	<% end %>
	<%= yield %>		
</main>

<aside class="sidebar">
</aside>

<%= render '/layouts/footer' %>

</body>
<%= debug(params) if Rails.env.development? %>
</html>

app/views/shared/_error_messages.html.erb
<%# AKA /signup %>
<% if @user.errors.any? %>
  <div id="alert alert-error">
    <h2>Sorry, please fix <%= pluralize(@user.errors.count, "error") %>.</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<h1>My Character Types</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
  <%= link_to 'Log In', login_path %>
  <%= link_to 'Create Account', signup_path %>
</p>

app/views/users/_user.html.erb
<li>
	<ul class="list-item">			<%# will_paginate requires the varaible name to match collection name. user and users %>
		<li><%= gravatar_for user, size: 50 %></li>		
		<li><%= link_to user.username, user %></li>
		<% if current_user.admin? %>
			<li><%= user.id %></li>
			<li><%= user.email %></li>
		<% end %>
		<% if current_user?(user) || current_user.admin? %>
			<li><%= link_to 'edit', edit_user_path(user) %></li>
		<% end %>
		<% if current_user.admin? && !current_user?(user) %>
			<%# instead of destroy, voluntary self deactivate. activatable in the future. don't hide posts. username becomes anonymous or 'nuked' %>
			<%# instead of destroy, ban %>
			<li><%= link_to 'destroy', user_path(user),
															 method: :delete, 
															 data: { confirm: 'Are you sure?' } %></li>
		<% end %>
	</ul>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<h1>Edit Profile</h1>

<%= render 'shared/error_messages' %>

<%= gravatar_for @user %>
<a href="http://gravatar.com/emails">change</a>

<%#= form_for @post, as: :post, url: posts_path, html: { class: "new_post", id: "new_post" } do |f| %>
<div class="form"> 
<%= form_for @user do |u| %>
	<p>
		<%= u.label :username %>:
		<%= u.text_field :username %>
	</p>
	<p>
		<%= u.label :email %>:
		<%= u.text_field :email %>
	</p>
	<p>
		<%= u.label :password %>:
		<%= u.password_field :password %>
	</p>
	<p>
		<%= u.label :password_confirmation, "Confirm Password" %>:
		<%= u.password_field :password_confirmation %>
	</p>
	<p>		
		<%# behavior is it goes back once. make it go back to previous link that is not the same page? %>
		<%= link_to "Back", :back %>
		<%= u.submit 'Save Changes', class: "btn" %>
	</p>
<%end%>



</div>

app/views/users/index.html.erb
<% provide(:title, 'Members') %>
<h1>Members</h1>

<%= will_paginate %>

<ul class="list">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Create Account') %>
<h1>Create Account</h1>

<%= render 'shared/error_messages' %>

<%#= form_for @post, as: :post, url: posts_path, html: { class: "new_post", id: "new_post" } do |f| %>
<div class="form"> 
<%= form_for @user do |u| %>
	<p>
		<%= u.label :username %>:
		<%= u.text_field :username %>
	</p>
	<p>
		<%= u.label :email %>:
		<%= u.text_field :email %>
	</p>
	<p>
		<%= u.label :password %>:
		<%= u.password_field :password %>
	</p>
	<p>
		<%= u.label :password_confirmation, "Confirm Password" %>:
		<%= u.password_field :password_confirmation %>
	</p>
	<p>
		<%# Find out how to edit text of the submit button to say something else like "Sign Up"%>		
		<%= link_to "Back", :back %>
		<%= u.submit 'Create Account' %>
	</p>
<%end%>
</div>

app/views/users/show.html.erb
<%= provide(:title, 'Profile') %>

<h1>Profile</h1>
<div>
	<%= gravatar_for @user %>
	<%= @user.username %>
</div>
<%= link_to "Edit Profile", edit_user_path(@user) %>
<%= link_to 'Settings', '#' %>
<div>
	<%= @user.username %>
	<br>
	<%# allow user to choose to either show or hide to other users%>
	<%= @user.email %>
	<br>
	<%#! Show edit button if logged in user matches the user of the profile %>
	<%# if @user.remember_token == current_user.remember_token %>
		<%#= link_to 'Edit profile', edit_user_path(@user) %>
	<%# end %>
</div>